apiVersion: v1 
kind: ConfigMap 
metadata: 
  name: aws-auth 
  namespace: kube-system 
data: 
  mapUsers: | 
    - userarn: arn:aws:iam::262016238917:user/eks-super-admin
      username: eks-super-admin
      groups:
        - system:masters